---
- include_tasks: "{{ansible_os_family|lower}}.yml"

- name: Create Installation Directories
  file:
    name: "{{item}}"
    state: directory
    recurse: yes
  with_items:
    - "{{vault_root}}"
    - "{{vault_install_dir}}"
    - "{{vault_bin_dir}}"

# we are using wget as the regular unarchive doesnt work
# - name: Install Vault
#   unarchive:
#     src: "https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_{{ansible_system|lower}}_amd64.zip"
#     dest: "/opt/vault/{{vault_version}}/"
#     remote_src: yes

- name: Download Vault
  command: wget -q https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_{{ansible_system|lower}}_amd64.zip -O {{vault_temp_dir}}/vault_{{vault_version}}_{{ansible_system|lower}}_amd64.zip

- name: Install Vault
  unarchive:
    src: "{{vault_temp_dir}}/vault_{{vault_version}}_{{ansible_system|lower}}_amd64.zip"
    dest: "{{vault_install_dir}}/"

- name: Link vault into {{vault_bin_dir}}
  file:
    src: "{{vault_install_dir}}/vault"
    dest: "{{vault_bin_dir}}/vault"
    state: link

- name: Add vault $PATH to system bash profile
  template:
    src: vault.sh.j2
    dest: "{{vault_profile_path[ansible_os_family]}}/vault.sh"
    mode: "0755"
